# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'direccionamientoLocal.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!
import ctypes
import paramiko
from PyQt5 import QtCore, QtGui, QtWidgets
import datetime
import configuracionBasica
import funciones2
import funciones_com
import time




class Ui_DireccionamientoLocal(object):
    def habilitadorInt1(self):
        self.txt_ip1_1.setEnabled(True)
        self.txt_ip1_2.setEnabled(True)
        self.txt_ip1_3.setEnabled(True)
        self.txt_ip1_4.setEnabled(True)
        self.txt_mask1_1.setEnabled(True)
        self.txt_mask1_2.setEnabled(True)
        self.txt_mask1_3.setEnabled(True)
        self.txt_mask1_4.setEnabled(True)

    def habilitadorInt2(self):
        self.habilitadorInt1()
        self.txt_ip2_1.setEnabled(True)
        self.txt_ip2_2.setEnabled(True)
        self.txt_ip2_3.setEnabled(True)
        self.txt_ip2_4.setEnabled(True)
        self.txt_mask2_1.setEnabled(True)
        self.txt_mask2_2.setEnabled(True)
        self.txt_mask2_3.setEnabled(True)
        self.txt_mask2_4.setEnabled(True)

    def habilitadorInt3(self):
        self.habilitadorInt2()
        self.txt_ip3_1.setEnabled(True)
        self.txt_ip3_2.setEnabled(True)
        self.txt_ip3_3.setEnabled(True)
        self.txt_ip3_4.setEnabled(True)
        self.txt_mask3_1.setEnabled(True)
        self.txt_mask3_2.setEnabled(True)
        self.txt_mask3_3.setEnabled(True)
        self.txt_mask3_4.setEnabled(True)

    def habilitadorInt4(self):
        self.habilitadorInt3()
        self.txt_ip4_1.setEnabled(True)
        self.txt_ip4_2.setEnabled(True)
        self.txt_ip4_3.setEnabled(True)
        self.txt_ip4_4.setEnabled(True)
        self.txt_mask4_1.setEnabled(True)
        self.txt_mask4_2.setEnabled(True)
        self.txt_mask4_3.setEnabled(True)
        self.txt_mask4_4.setEnabled(True)

    def habilitadorInt5(self):
        self.habilitadorInt4()
        self.txt_ip5_1.setEnabled(True)
        self.txt_ip5_2.setEnabled(True)
        self.txt_ip5_3.setEnabled(True)
        self.txt_ip5_4.setEnabled(True)
        self.txt_mask5_1.setEnabled(True)
        self.txt_mask5_2.setEnabled(True)
        self.txt_mask5_3.setEnabled(True)
        self.txt_mask5_4.setEnabled(True)

    def habilitadorCampos(self, interfaces):
        n = len(interfaces)
        if n == 0:
            ctypes.windll.user32.MessageBoxW(0, "No existe ninguna interfaz disponible para configurar", "Error", 1)
        elif n == 1:
            self.lbl_int1.setText(interfaces[0][0])
            self.lbl_int1.setEnabled(True)
            self.habilitadorInt1()
        elif n == 2:
            self.lbl_int1.setText(interfaces[0][0])
            self.lbl_int1.setEnabled(True)
            self.lbl_int2.setText(interfaces[1][0])
            self.lbl_int2.setEnabled(True)
            self.habilitadorInt2()
        elif n == 3:
            self.lbl_int1.setText(interfaces[0][0])
            self.lbl_int1.setEnabled(True)
            self.lbl_int2.setText(interfaces[1][0])
            self.lbl_int2.setEnabled(True)
            self.lbl_int3.setText(interfaces[2][0])
            self.lbl_int3.setEnabled(True)
            self.habilitadorInt3()
        elif n == 4:
            self.lbl_int1.setText(interfaces[0][0])
            self.lbl_int1.setEnabled(True)
            self.lbl_int2.setText(interfaces[1][0])
            self.lbl_int2.setEnabled(True)
            self.lbl_int3.setText(interfaces[2][0])
            self.lbl_int3.setEnabled(True)
            self.lbl_int4.setText(interfaces[3][0])
            self.lbl_int4.setEnabled(True)
            self.habilitadorInt4()
        elif n >= 5:
            self.lbl_int1.setText(interfaces[0][0])
            self.lbl_int1.setEnabled(True)
            self.lbl_int2.setText(interfaces[1][0])
            self.lbl_int2.setEnabled(True)
            self.lbl_int3.setText(interfaces[2][0])
            self.lbl_int3.setEnabled(True)
            self.lbl_int4.setText(interfaces[3][0])
            self.lbl_int4.setEnabled(True)
            self.lbl_int5.setText(interfaces[4][0])
            self.lbl_int5.setEnabled(True)
            self.habilitadorInt5()

    def setSegundaIp(self, int, remote_conn):
        m1 = self.txt_mask2_1.text()
        m2 = self.txt_mask2_2.text()
        m3 = self.txt_mask2_3.text()
        m4 = self.txt_mask2_4.text()
        ip1 = self.txt_ip2_1.text()
        ip2 = self.txt_ip2_2.text()
        ip3 = self.txt_ip2_3.text()
        ip4 = self.txt_ip2_4.text()
        valIp = ip1 + ip2 + ip3 + ip4
        valMask = m1 + m2 + m3 + m4
        print ("a")
        if (valIp != "" and valMask != ""):
            print("b")
            ip = ip1 + "." + ip2 + "." + ip3 + "." + ip4
            mask = m1 + "." + m2 + "." + m3 + "." + m4
            if(type(remote_conn) is paramiko.channel.Channel):
                funciones2.config_dir(remote_conn, int, ip, mask)
                ctypes.windll.user32.MessageBoxW(0, "Se configuro la interfaz" + int,
                                                 "Exito", 0)
            else:
                funciones_com.config_dir(remote_conn, int, ip, mask)
    def setPrimeraIp(self, int, remote_conn):
        m1 = self.txt_mask1_1.text()
        m2 = self.txt_mask1_2.text()
        m3 = self.txt_mask1_3.text()
        m4 = self.txt_mask1_4.text()
        ip1 = self.txt_ip1_1.text()
        ip2 = self.txt_ip1_2.text()
        ip3 = self.txt_ip1_3.text()
        ip4 = self.txt_ip1_4.text()
        valIp = ip1 + ip2 + ip3 + ip4
        valMask = m1 + m2 + m3 + m4
        if (valIp != "" and valMask != ""):
            ip = ip1 + "." + ip2 + "." + ip3 + "." + ip4
            mask = m1 + "." + m2 + "." + m3 + "." + m4
            if (type(remote_conn) is paramiko.channel.Channel):
                funciones2.config_dir(remote_conn, int, ip, mask)
                ctypes.windll.user32.MessageBoxW(0, "Se configuro la interfaz" + int,
                                                 "Exito", 0)
            else:
                funciones_com.config_dir(remote_conn, int, ip, mask)
    def setTerceraIp(self, int, remote_conn):
        m1 = self.txt_mask3_1.text()
        m2 = self.txt_mask3_2.text()
        m3 = self.txt_mask3_3.text()
        m4 = self.txt_mask3_4.text()
        ip1 = self.txt_ip3_1.text()
        ip2 = self.txt_ip3_2.text()
        ip3 = self.txt_ip3_3.text()
        ip4 = self.txt_ip3_4.text()
        valIp = ip1 + ip2 + ip3 + ip4
        valMask = m1 + m2 + m3 + m4
        if (valIp != "" and valMask != ""):
            ip = ip1 + "." + ip2 + "." + ip3 + "." + ip4
            mask = m1 + "." + m2 + "." + m3 + "." + m4
            if (type(remote_conn) is paramiko.channel.Channel):
                funciones2.config_dir(remote_conn, int, ip, mask)
                ctypes.windll.user32.MessageBoxW(0, "Se configuro la interfaz" + int,
                                                 "Exito", 0)
            else:
                funciones_com.config_dir(remote_conn, int, ip, mask)
    def setCuartaIp(self, int, remote_conn):
        m1 = self.txt_mask4_1.text()
        m2 = self.txt_mask4_2.text()
        m3 = self.txt_mask4_3.text()
        m4 = self.txt_mask4_4.text()
        ip1 = self.txt_ip4_1.text()
        ip2 = self.txt_ip4_2.text()
        ip3 = self.txt_ip4_3.text()
        ip4 = self.txt_ip4_4.text()
        valIp = ip1  + ip2 + ip3  + ip4
        valMask = m1 +  m2  + m3  + m4
        if(valIp != "" and valMask != ""):
            ip = ip1 + "." + ip2 + "." + ip3 + "." + ip4
            mask = m1 + "." + m2 + "." + m3 + "." + m4
            if (type(remote_conn) is paramiko.channel.Channel):
                funciones2.config_dir(remote_conn, int, ip, mask)
                ctypes.windll.user32.MessageBoxW(0, "Se configuro la interfaz" + int,
                                                 "Exito", 0)
            else:
                funciones_com.config_dir(remote_conn, int, ip, mask)

    def setQuintaIp(self, int, remote_conn):
        m1 = self.txt_mask4_1.text()
        m2 = self.txt_mask4_2.text()
        m3 = self.txt_mask4_3.text()
        m4 = self.txt_mask4_4.text()
        ip1 = self.txt_ip4_1.text()
        ip2 = self.txt_ip4_2.text()
        ip3 = self.txt_ip4_3.text()
        ip4 = self.txt_ip4_4.text()
        valIp = ip1  + ip2 + ip3  + ip4
        valMask = m1 +  m2  + m3  + m4
        if(valIp != "" and valMask != ""):
            ip = ip1 + "." + ip2 + "." + ip3 + "." + ip4
            mask = m1 + "." + m2 + "." + m3 + "." + m4
            if (type(remote_conn) is paramiko.channel.Channel):
                funciones2.config_dir(remote_conn, int, ip, mask)
                ctypes.windll.user32.MessageBoxW(0, "Se configuro la interfaz"+int,
                                                 "Exito", 0)
            else:
                funciones_com.config_dir(remote_conn, int, ip, mask)


    def setLoopBack(self, int, remote_conn):
        m1 = self.txt_maskL1.text()
        m2 = self.txt_maskL2.text()
        m3 = self.txt_maskL3.text()
        m4 = self.txt_maskL4.text()
        ip1 = self.txt_ipL1.text()
        ip2 = self.txt_ipL2.text()
        ip3 = self.txt_ipL3.text()
        ip4 = self.txt_ipL4.text()
        self.valIp = ip1  + ip2 + ip3  + ip4
        valMask = m1 +  m2  + m3  + m4
        if(self.valIp != "" and valMask != ""):
            ip = ip1 + "." + ip2 + "." + ip3 + "." + ip4
            mask = m1 + "." + m2 + "." + m3 + "." + m4
            if (type(remote_conn) is paramiko.channel.Channel):
                funciones2.config_dir(remote_conn, int, ip, mask)
                ctypes.windll.user32.MessageBoxW(0, "Se configuro la interfaz" + int,
                                                 "Exito", 0)
            else:
                funciones_com.config_dir(remote_conn, int, ip, mask)

    def setDireccionamiento(self, remote_conn, interfaces):
        print("0")
        try:
            self.setPrimeraIp(interfaces[0][0],remote_conn)
        except Exception:
            print("IndexOut")
        print("1")
        try:
            self.setSegundaIp(interfaces[1][0], remote_conn)
        except Exception:
            print("IndexOut")
        print("2")
        try:
            self.setTerceraIp(interfaces[2][0], remote_conn)
        except Exception:
            print("IndexOut")
        print("3")
        try:
            self.setCuartaIp(interfaces[3][0], remote_conn)
        except Exception:
            print("IndexOut")
        print("4")
        try:
            self.setQuintaIp(interfaces[4][0], remote_conn)
        except Exception:
            print("IndexOut")
        print("4")
        self.setLoopBack("LoopBack 0", remote_conn)
        print("5")
        time.sleep(1)
        funciones2.config_OSPF(remote_conn)
        time.sleep(1)
        ctypes.windll.user32.MessageBoxW(0, "Configuración finalizada",
                                         "Done", 0)



    def atras(self,DireccionamientoLocal, remote_cnn):
        self.configuracionBasica = QtWidgets.QDialog()
        self.ui = configuracionBasica.Ui_ConfiguracionBasica()
        self.ui.setupUi(self.configuracionBasica, remote_cnn)
        self.configuracionBasica.show()
        DireccionamientoLocal.close()



    def setupUi(self, DireccionamientoLocal, remote_conn):
        DireccionamientoLocal.setObjectName("DireccionamientoLocal")
        DireccionamientoLocal.resize(727, 480)
        self.label = QtWidgets.QLabel(DireccionamientoLocal)
        self.label.setGeometry(QtCore.QRect(80, 40, 55, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_2.setGeometry(QtCore.QRect(270, 40, 71, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_3.setGeometry(QtCore.QRect(490, 40, 55, 16))
        self.label_3.setObjectName("label_3")
        self.lbl_int1 = QtWidgets.QLabel(DireccionamientoLocal)
        self.lbl_int1.setEnabled(False)
        self.lbl_int1.setGeometry(QtCore.QRect(30, 130, 131, 20))
        self.lbl_int1.setObjectName("lbl_int1")
        self.label_11 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_11.setEnabled(False)
        self.label_11.setGeometry(QtCore.QRect(290, 140, 16, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_12.setEnabled(False)
        self.label_12.setGeometry(QtCore.QRect(340, 140, 16, 16))
        self.label_12.setObjectName("label_12")
        self.txt_ip1_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip1_1.setEnabled(False)
        self.txt_ip1_1.setGeometry(QtCore.QRect(200, 130, 31, 22))
        self.txt_ip1_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip1_1.setMaxLength(3)
        self.txt_ip1_1.setObjectName("txt_ip1_1")
        self.label_13 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_13.setEnabled(False)
        self.label_13.setGeometry(QtCore.QRect(240, 140, 16, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_14.setEnabled(False)
        self.label_14.setGeometry(QtCore.QRect(510, 140, 16, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_15.setEnabled(False)
        self.label_15.setGeometry(QtCore.QRect(560, 140, 16, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_16.setEnabled(False)
        self.label_16.setGeometry(QtCore.QRect(460, 140, 16, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_17.setEnabled(False)
        self.label_17.setGeometry(QtCore.QRect(460, 190, 16, 16))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_18.setEnabled(False)
        self.label_18.setGeometry(QtCore.QRect(240, 190, 16, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_19.setEnabled(False)
        self.label_19.setGeometry(QtCore.QRect(510, 190, 16, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_20.setEnabled(False)
        self.label_20.setGeometry(QtCore.QRect(290, 190, 16, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_21.setEnabled(False)
        self.label_21.setGeometry(QtCore.QRect(340, 190, 16, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_22.setEnabled(False)
        self.label_22.setGeometry(QtCore.QRect(560, 190, 16, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_23.setEnabled(False)
        self.label_23.setGeometry(QtCore.QRect(460, 240, 16, 16))
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_24.setEnabled(False)
        self.label_24.setGeometry(QtCore.QRect(240, 240, 16, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_25.setEnabled(False)
        self.label_25.setGeometry(QtCore.QRect(510, 240, 16, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_26.setEnabled(False)
        self.label_26.setGeometry(QtCore.QRect(290, 240, 16, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_27.setEnabled(False)
        self.label_27.setGeometry(QtCore.QRect(340, 240, 16, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_28.setEnabled(False)
        self.label_28.setGeometry(QtCore.QRect(560, 240, 16, 16))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_29.setEnabled(False)
        self.label_29.setGeometry(QtCore.QRect(460, 290, 16, 16))
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_30.setEnabled(False)
        self.label_30.setGeometry(QtCore.QRect(240, 290, 16, 16))
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_31.setEnabled(False)
        self.label_31.setGeometry(QtCore.QRect(510, 290, 16, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_32.setEnabled(False)
        self.label_32.setGeometry(QtCore.QRect(290, 290, 16, 16))
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_33.setEnabled(False)
        self.label_33.setGeometry(QtCore.QRect(340, 290, 16, 16))
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_34.setEnabled(False)
        self.label_34.setGeometry(QtCore.QRect(560, 290, 16, 16))
        self.label_34.setObjectName("label_34")
        self.btn_enviar = QtWidgets.QPushButton(DireccionamientoLocal)
        self.btn_enviar.setGeometry(QtCore.QRect(260, 400, 93, 28))
        self.btn_enviar.setObjectName("btn_enviar")
        self.lbl_int2 = QtWidgets.QLabel(DireccionamientoLocal)
        self.lbl_int2.setEnabled(False)
        self.lbl_int2.setGeometry(QtCore.QRect(30, 180, 131, 20))
        self.lbl_int2.setObjectName("lbl_int2")
        self.lbl_int3 = QtWidgets.QLabel(DireccionamientoLocal)
        self.lbl_int3.setEnabled(False)
        self.lbl_int3.setGeometry(QtCore.QRect(30, 230, 131, 20))
        self.lbl_int3.setObjectName("lbl_int3")
        self.lbl_int4 = QtWidgets.QLabel(DireccionamientoLocal)
        self.lbl_int4.setEnabled(False)
        self.lbl_int4.setGeometry(QtCore.QRect(30, 280, 131, 20))
        self.lbl_int4.setObjectName("lbl_int4")
        self.lbl_int5 = QtWidgets.QLabel(DireccionamientoLocal)
        self.lbl_int5.setEnabled(False)
        self.lbl_int5.setGeometry(QtCore.QRect(30, 330, 131, 20))
        self.lbl_int5.setObjectName("lbl_int5")
        self.txt_ip1_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip1_2.setEnabled(False)
        self.txt_ip1_2.setGeometry(QtCore.QRect(250, 130, 31, 22))
        self.txt_ip1_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip1_2.setMaxLength(3)
        self.txt_ip1_2.setObjectName("txt_ip1_2")
        self.txt_ip1_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip1_3.setEnabled(False)
        self.txt_ip1_3.setGeometry(QtCore.QRect(300, 130, 31, 22))
        self.txt_ip1_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip1_3.setMaxLength(3)
        self.txt_ip1_3.setObjectName("txt_ip1_3")
        self.txt_ip1_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip1_4.setEnabled(False)
        self.txt_ip1_4.setGeometry(QtCore.QRect(350, 130, 31, 22))
        self.txt_ip1_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip1_4.setMaxLength(3)
        self.txt_ip1_4.setObjectName("txt_ip1_4")
        self.txt_mask1_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask1_1.setEnabled(False)
        self.txt_mask1_1.setGeometry(QtCore.QRect(420, 130, 31, 22))
        self.txt_mask1_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask1_1.setMaxLength(3)
        self.txt_mask1_1.setObjectName("txt_mask1_1")
        self.txt_mask1_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask1_2.setEnabled(False)
        self.txt_mask1_2.setGeometry(QtCore.QRect(470, 130, 31, 22))
        self.txt_mask1_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask1_2.setMaxLength(3)
        self.txt_mask1_2.setObjectName("txt_mask1_2")
        self.txt_mask1_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask1_4.setEnabled(False)
        self.txt_mask1_4.setGeometry(QtCore.QRect(570, 130, 31, 22))
        self.txt_mask1_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask1_4.setMaxLength(3)
        self.txt_mask1_4.setObjectName("txt_mask1_4")
        self.txt_mask1_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask1_3.setEnabled(False)
        self.txt_mask1_3.setGeometry(QtCore.QRect(520, 130, 31, 22))
        self.txt_mask1_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask1_3.setMaxLength(3)
        self.txt_mask1_3.setObjectName("txt_mask1_3")
        self.txt_ip2_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip2_3.setEnabled(False)
        self.txt_ip2_3.setGeometry(QtCore.QRect(300, 180, 31, 22))
        self.txt_ip2_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip2_3.setMaxLength(3)
        self.txt_ip2_3.setObjectName("txt_ip2_3")
        self.txt_mask2_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask2_2.setEnabled(False)
        self.txt_mask2_2.setGeometry(QtCore.QRect(470, 180, 31, 22))
        self.txt_mask2_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask2_2.setMaxLength(3)
        self.txt_mask2_2.setObjectName("txt_mask2_2")
        self.txt_ip2_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip2_2.setEnabled(False)
        self.txt_ip2_2.setGeometry(QtCore.QRect(250, 180, 31, 22))
        self.txt_ip2_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip2_2.setMaxLength(3)
        self.txt_ip2_2.setObjectName("txt_ip2_2")
        self.txt_ip2_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip2_4.setEnabled(False)
        self.txt_ip2_4.setGeometry(QtCore.QRect(350, 180, 31, 22))
        self.txt_ip2_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip2_4.setMaxLength(3)
        self.txt_ip2_4.setObjectName("txt_ip2_4")
        self.txt_mask2_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask2_1.setEnabled(False)
        self.txt_mask2_1.setGeometry(QtCore.QRect(420, 180, 31, 22))
        self.txt_mask2_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask2_1.setMaxLength(3)
        self.txt_mask2_1.setObjectName("txt_mask2_1")
        self.txt_mask2_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask2_3.setEnabled(False)
        self.txt_mask2_3.setGeometry(QtCore.QRect(520, 180, 31, 22))
        self.txt_mask2_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask2_3.setMaxLength(3)
        self.txt_mask2_3.setObjectName("txt_mask2_3")
        self.txt_ip2_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip2_1.setEnabled(False)
        self.txt_ip2_1.setGeometry(QtCore.QRect(200, 180, 31, 22))
        self.txt_ip2_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip2_1.setText("")
        self.txt_ip2_1.setMaxLength(3)
        self.txt_ip2_1.setObjectName("txt_ip2_1")
        self.txt_mask1_8 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask1_8.setGeometry(QtCore.QRect(730, 180, 31, 22))
        self.txt_mask1_8.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask1_8.setMaxLength(3)
        self.txt_mask1_8.setObjectName("txt_mask1_8")
        self.txt_mask2_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask2_4.setEnabled(False)
        self.txt_mask2_4.setGeometry(QtCore.QRect(570, 180, 31, 22))
        self.txt_mask2_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask2_4.setMaxLength(3)
        self.txt_mask2_4.setObjectName("txt_mask2_4")
        self.txt_ip3_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip3_3.setEnabled(False)
        self.txt_ip3_3.setGeometry(QtCore.QRect(300, 230, 31, 22))
        self.txt_ip3_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip3_3.setMaxLength(3)
        self.txt_ip3_3.setObjectName("txt_ip3_3")
        self.txt_mask3_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask3_2.setEnabled(False)
        self.txt_mask3_2.setGeometry(QtCore.QRect(470, 230, 31, 22))
        self.txt_mask3_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask3_2.setMaxLength(3)
        self.txt_mask3_2.setObjectName("txt_mask3_2")
        self.txt_ip3_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip3_2.setEnabled(False)
        self.txt_ip3_2.setGeometry(QtCore.QRect(250, 230, 31, 22))
        self.txt_ip3_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip3_2.setMaxLength(3)
        self.txt_ip3_2.setObjectName("txt_ip3_2")
        self.txt_mask4_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask4_1.setEnabled(False)
        self.txt_mask4_1.setGeometry(QtCore.QRect(420, 280, 31, 22))
        self.txt_mask4_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask4_1.setMaxLength(3)
        self.txt_mask4_1.setObjectName("txt_mask4_1")
        self.txt_ip3_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip3_4.setEnabled(False)
        self.txt_ip3_4.setGeometry(QtCore.QRect(350, 230, 31, 22))
        self.txt_ip3_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip3_4.setMaxLength(3)
        self.txt_ip3_4.setObjectName("txt_ip3_4")
        self.txt_mask4_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask4_3.setEnabled(False)
        self.txt_mask4_3.setGeometry(QtCore.QRect(520, 280, 31, 22))
        self.txt_mask4_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask4_3.setMaxLength(3)
        self.txt_mask4_3.setObjectName("txt_mask4_3")
        self.txt_ip4_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip4_4.setEnabled(False)
        self.txt_ip4_4.setGeometry(QtCore.QRect(350, 280, 31, 22))
        self.txt_ip4_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip4_4.setMaxLength(3)
        self.txt_ip4_4.setObjectName("txt_ip4_4")
        self.txt_ip4_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip4_3.setEnabled(False)
        self.txt_ip4_3.setGeometry(QtCore.QRect(300, 280, 31, 22))
        self.txt_ip4_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip4_3.setMaxLength(3)
        self.txt_ip4_3.setObjectName("txt_ip4_3")
        self.txt_ip4_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip4_1.setEnabled(False)
        self.txt_ip4_1.setGeometry(QtCore.QRect(200, 280, 31, 22))
        self.txt_ip4_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip4_1.setText("")
        self.txt_ip4_1.setMaxLength(3)
        self.txt_ip4_1.setObjectName("txt_ip4_1")
        self.txt_mask4_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask4_4.setEnabled(False)
        self.txt_mask4_4.setGeometry(QtCore.QRect(570, 280, 31, 22))
        self.txt_mask4_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask4_4.setMaxLength(3)
        self.txt_mask4_4.setObjectName("txt_mask4_4")
        self.txt_mask3_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask3_1.setEnabled(False)
        self.txt_mask3_1.setGeometry(QtCore.QRect(420, 230, 31, 22))
        self.txt_mask3_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask3_1.setMaxLength(3)
        self.txt_mask3_1.setObjectName("txt_mask3_1")
        self.txt_mask3_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask3_3.setEnabled(False)
        self.txt_mask3_3.setGeometry(QtCore.QRect(520, 230, 31, 22))
        self.txt_mask3_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask3_3.setMaxLength(3)
        self.txt_mask3_3.setObjectName("txt_mask3_3")
        self.txt_ip3_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip3_1.setEnabled(False)
        self.txt_ip3_1.setGeometry(QtCore.QRect(200, 230, 31, 22))
        self.txt_ip3_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip3_1.setMaxLength(3)
        self.txt_ip3_1.setObjectName("txt_ip3_1")
        self.txt_mask3_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask3_4.setEnabled(False)
        self.txt_mask3_4.setGeometry(QtCore.QRect(570, 230, 31, 22))
        self.txt_mask3_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask3_4.setMaxLength(3)
        self.txt_mask3_4.setObjectName("txt_mask3_4")
        self.txt_ip4_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip4_2.setEnabled(False)
        self.txt_ip4_2.setGeometry(QtCore.QRect(250, 280, 31, 22))
        self.txt_ip4_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip4_2.setMaxLength(3)
        self.txt_ip4_2.setObjectName("txt_ip4_2")
        self.txt_mask4_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask4_2.setEnabled(False)
        self.txt_mask4_2.setGeometry(QtCore.QRect(470, 280, 31, 22))
        self.txt_mask4_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask4_2.setMaxLength(3)
        self.txt_mask4_2.setObjectName("txt_mask4_2")
        self.txt_ip5_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip5_3.setEnabled(False)
        self.txt_ip5_3.setGeometry(QtCore.QRect(300, 330, 31, 22))
        self.txt_ip5_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip5_3.setMaxLength(3)
        self.txt_ip5_3.setObjectName("txt_ip5_3")
        self.txt_mask5_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask5_2.setEnabled(False)
        self.txt_mask5_2.setGeometry(QtCore.QRect(470, 330, 31, 22))
        self.txt_mask5_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask5_2.setMaxLength(3)
        self.txt_mask5_2.setObjectName("txt_mask5_2")
        self.txt_ip5_2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip5_2.setEnabled(False)
        self.txt_ip5_2.setGeometry(QtCore.QRect(250, 330, 31, 22))
        self.txt_ip5_2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip5_2.setMaxLength(3)
        self.txt_ip5_2.setObjectName("txt_ip5_2")
        self.txt_ip5_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip5_4.setEnabled(False)
        self.txt_ip5_4.setGeometry(QtCore.QRect(350, 330, 31, 22))
        self.txt_ip5_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip5_4.setMaxLength(3)
        self.txt_ip5_4.setObjectName("txt_ip5_4")
        self.txt_mask5_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask5_1.setEnabled(False)
        self.txt_mask5_1.setGeometry(QtCore.QRect(420, 330, 31, 22))
        self.txt_mask5_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask5_1.setMaxLength(3)
        self.txt_mask5_1.setObjectName("txt_mask5_1")
        self.txt_mask5_3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask5_3.setEnabled(False)
        self.txt_mask5_3.setGeometry(QtCore.QRect(520, 330, 31, 22))
        self.txt_mask5_3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask5_3.setMaxLength(3)
        self.txt_mask5_3.setObjectName("txt_mask5_3")
        self.txt_ip5_1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ip5_1.setEnabled(False)
        self.txt_ip5_1.setGeometry(QtCore.QRect(200, 330, 31, 22))
        self.txt_ip5_1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ip5_1.setMaxLength(3)
        self.txt_ip5_1.setObjectName("txt_ip5_1")
        self.txt_mask5_4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_mask5_4.setEnabled(False)
        self.txt_mask5_4.setGeometry(QtCore.QRect(570, 330, 31, 22))
        self.txt_mask5_4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_mask5_4.setMaxLength(3)
        self.txt_mask5_4.setObjectName("txt_mask5_4")
        self.label_35 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_35.setEnabled(False)
        self.label_35.setGeometry(QtCore.QRect(240, 340, 16, 16))
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_36.setEnabled(False)
        self.label_36.setGeometry(QtCore.QRect(290, 340, 16, 16))
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_37.setEnabled(False)
        self.label_37.setGeometry(QtCore.QRect(460, 340, 16, 16))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_38.setEnabled(False)
        self.label_38.setGeometry(QtCore.QRect(560, 340, 16, 16))
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_39.setEnabled(False)
        self.label_39.setGeometry(QtCore.QRect(340, 340, 16, 16))
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_40.setEnabled(False)
        self.label_40.setGeometry(QtCore.QRect(510, 340, 16, 16))
        self.label_40.setObjectName("label_40")
        self.btn_cancelar = QtWidgets.QPushButton(DireccionamientoLocal)
        self.btn_cancelar.setGeometry(QtCore.QRect(440, 400, 93, 28))
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.label_41 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_41.setEnabled(False)
        self.label_41.setGeometry(QtCore.QRect(240, 90, 16, 16))
        self.label_41.setObjectName("label_41")
        self.txt_maskL1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_maskL1.setEnabled(True)
        self.txt_maskL1.setGeometry(QtCore.QRect(420, 80, 31, 22))
        self.txt_maskL1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_maskL1.setMaxLength(3)
        self.txt_maskL1.setObjectName("txt_maskL1")
        self.label_42 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_42.setEnabled(True)
        self.label_42.setGeometry(QtCore.QRect(560, 90, 16, 16))
        self.label_42.setObjectName("label_42")
        self.txt_ipL2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ipL2.setEnabled(True)
        self.txt_ipL2.setGeometry(QtCore.QRect(250, 80, 31, 22))
        self.txt_ipL2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ipL2.setMaxLength(3)
        self.txt_ipL2.setObjectName("txt_ipL2")
        self.label_43 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_43.setEnabled(True)
        self.label_43.setGeometry(QtCore.QRect(510, 90, 16, 16))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_44.setEnabled(True)
        self.label_44.setGeometry(QtCore.QRect(340, 90, 16, 16))
        self.label_44.setObjectName("label_44")
        self.lbl_int1_2 = QtWidgets.QLabel(DireccionamientoLocal)
        self.lbl_int1_2.setEnabled(True)
        self.lbl_int1_2.setGeometry(QtCore.QRect(30, 80, 131, 20))
        self.lbl_int1_2.setObjectName("lbl_int1_2")
        self.txt_maskL3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_maskL3.setEnabled(True)
        self.txt_maskL3.setGeometry(QtCore.QRect(520, 80, 31, 22))
        self.txt_maskL3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_maskL3.setMaxLength(3)
        self.txt_maskL3.setObjectName("txt_maskL3")
        self.label_45 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_45.setEnabled(True)
        self.label_45.setGeometry(QtCore.QRect(290, 90, 16, 16))
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(DireccionamientoLocal)
        self.label_46.setEnabled(True)
        self.label_46.setGeometry(QtCore.QRect(460, 90, 16, 16))
        self.label_46.setObjectName("label_46")
        self.txt_maskL2 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_maskL2.setEnabled(True)
        self.txt_maskL2.setGeometry(QtCore.QRect(470, 80, 31, 22))
        self.txt_maskL2.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_maskL2.setMaxLength(3)
        self.txt_maskL2.setObjectName("txt_maskL2")
        self.txt_ipL1 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ipL1.setEnabled(True)
        self.txt_ipL1.setGeometry(QtCore.QRect(200, 80, 31, 22))
        self.txt_ipL1.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ipL1.setMaxLength(3)
        self.txt_ipL1.setObjectName("txt_ipL1")
        self.txt_ipL4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ipL4.setEnabled(True)
        self.txt_ipL4.setGeometry(QtCore.QRect(350, 80, 31, 22))
        self.txt_ipL4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ipL4.setMaxLength(3)
        self.txt_ipL4.setObjectName("txt_ipL4")
        self.txt_maskL4 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_maskL4.setEnabled(True)
        self.txt_maskL4.setGeometry(QtCore.QRect(570, 80, 31, 22))
        self.txt_maskL4.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_maskL4.setMaxLength(3)
        self.txt_maskL4.setObjectName("txt_maskL4")
        self.txt_ipL3 = QtWidgets.QLineEdit(DireccionamientoLocal)
        self.txt_ipL3.setEnabled(True)
        self.txt_ipL3.setGeometry(QtCore.QRect(300, 80, 31, 22))
        self.txt_ipL3.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.txt_ipL3.setMaxLength(3)
        self.txt_ipL3.setObjectName("txt_ipL3")
        self.retranslateUi(DireccionamientoLocal)
        QtCore.QMetaObject.connectSlotsByName(DireccionamientoLocal)
        ##################################################################
        print("wq")
        interfaces = []
        if (type(remote_conn) is paramiko.channel.Channel):
             interfaces = funciones2.get_ip_interfaz(remote_conn)
        else:
            interfaces = funciones_com.get_ip_interfaz(remote_conn)
        print("a", interfaces)
        #interfaces = [["fa1","up"],["fa2",'down'],["sdfsd","adf"]]
        self.habilitadorCampos(interfaces)
        self.btn_enviar.clicked.connect(lambda : self.setDireccionamiento(remote_conn, interfaces))
        self.btn_cancelar.clicked.connect(lambda : self.atras(DireccionamientoLocal, remote_conn))
        

    def retranslateUi(self, DireccionamientoLocal):
        _translate = QtCore.QCoreApplication.translate
        DireccionamientoLocal.setWindowTitle(_translate("DireccionamientoLocal", "Form"))
        self.label.setText(_translate("DireccionamientoLocal", "Interfaz"))
        self.label_2.setText(_translate("DireccionamientoLocal", "Direccion IP"))
        self.label_3.setText(_translate("DireccionamientoLocal", "Mascara"))
        self.lbl_int1.setText(_translate("DireccionamientoLocal", "-"))
        self.label_11.setText(_translate("DireccionamientoLocal", "."))
        self.label_12.setText(_translate("DireccionamientoLocal", "."))
        self.label_13.setText(_translate("DireccionamientoLocal", "."))
        self.label_14.setText(_translate("DireccionamientoLocal", "."))
        self.label_15.setText(_translate("DireccionamientoLocal", "."))
        self.label_16.setText(_translate("DireccionamientoLocal", "."))
        self.label_17.setText(_translate("DireccionamientoLocal", "."))
        self.label_18.setText(_translate("DireccionamientoLocal", "."))
        self.label_19.setText(_translate("DireccionamientoLocal", "."))
        self.label_20.setText(_translate("DireccionamientoLocal", "."))
        self.label_21.setText(_translate("DireccionamientoLocal", "."))
        self.label_22.setText(_translate("DireccionamientoLocal", "."))
        self.label_23.setText(_translate("DireccionamientoLocal", "."))
        self.label_24.setText(_translate("DireccionamientoLocal", "."))
        self.label_25.setText(_translate("DireccionamientoLocal", "."))
        self.label_26.setText(_translate("DireccionamientoLocal", "."))
        self.label_27.setText(_translate("DireccionamientoLocal", "."))
        self.label_28.setText(_translate("DireccionamientoLocal", "."))
        self.label_29.setText(_translate("DireccionamientoLocal", "."))
        self.label_30.setText(_translate("DireccionamientoLocal", "."))
        self.label_31.setText(_translate("DireccionamientoLocal", "."))
        self.label_32.setText(_translate("DireccionamientoLocal", "."))
        self.label_33.setText(_translate("DireccionamientoLocal", "."))
        self.label_34.setText(_translate("DireccionamientoLocal", "."))
        self.btn_enviar.setText(_translate("DireccionamientoLocal", "Enviar"))
        self.lbl_int2.setText(_translate("DireccionamientoLocal", "-"))
        self.lbl_int3.setText(_translate("DireccionamientoLocal", "-"))
        self.lbl_int4.setText(_translate("DireccionamientoLocal", "-"))
        self.lbl_int5.setText(_translate("DireccionamientoLocal", "-"))
        self.label_35.setText(_translate("DireccionamientoLocal", "."))
        self.label_36.setText(_translate("DireccionamientoLocal", "."))
        self.label_37.setText(_translate("DireccionamientoLocal", "."))
        self.label_38.setText(_translate("DireccionamientoLocal", "."))
        self.label_39.setText(_translate("DireccionamientoLocal", "."))
        self.label_40.setText(_translate("DireccionamientoLocal", "."))
        self.btn_cancelar.setText(_translate("DireccionamientoLocal", "Atras"))
        self.label_41.setText(_translate("DireccionamientoLocal", "."))
        self.label_42.setText(_translate("DireccionamientoLocal", "."))
        self.label_43.setText(_translate("DireccionamientoLocal", "."))
        self.label_44.setText(_translate("DireccionamientoLocal", "."))
        self.lbl_int1_2.setText(_translate("DireccionamientoLocal", "LoopBack 0"))
        self.label_45.setText(_translate("DireccionamientoLocal", "."))
        self.label_46.setText(_translate("DireccionamientoLocal", "."))
